name: targeted_overlay
description: "A simple way to show overlays attached to target widgets."
version: 0.2.0+1
homepage: https://github.com/Kanyade/targeted-overlay
repository: https://github.com/Kanyade/targeted-overlay

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
